# Netlify Configuration for Geriatrics Platform
# https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  # No build command needed for static HTML site
  command = "echo 'Deploying static site'"
  publish = "."

[build.environment]
  NODE_VERSION = "18"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# Dev server settings
[dev]
  command = "npx live-server --port=8888"
  port = 8888
  autoLaunch = true
  framework = "#static"
