[build]
  publish = "."
  command = ""

[build.environment]
  NODE_VERSION = "20.11.1"

[[headers]]
  for = "/*"
  [headers.values]
    Strict-Transport-Security = "max-age=31536000; includeSubDomains; preload"
    X-Content-Type-Options = "nosniff"
    X-Frame-Options = "DENY"
    Referrer-Policy = "no-referrer"
    Permissions-Policy = "interest-cohort=()"
    Content-Security-Policy = "default-src 'self'; img-src 'self' data:; style-src 'self' 'unsafe-inline'; script-src 'self' 'unsafe-inline'; connect-src 'self'; object-src 'none'; base-uri 'self'; form-action 'self'"

[[headers]]
  for = "/public/data/*.json"
  [headers.values]
    Cache-Control = "max-age=300, must-revalidate"