# Netlify Configuration for Geriatrics Platform
# https://docs.netlify.com/configure-builds/file-based-configuration/

[build]
  # Build command for Vite React app
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--legacy-peer-deps"

# Production context
[context.production.environment]
  NODE_ENV = "production"

# Headers for security
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"

# SPA redirect for client-side routing
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Cache static assets
[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

# Dev server settings
[dev]
  command = "npm run dev"
  port = 5173
  autoLaunch = true
  framework = "#custom"
